"""initial_relay

Revision ID: 37373f664fa9
Revises: 
Create Date: 2026-08-20 15:31:46.698997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37373f664fa9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=False),
    sa.Column('reminder_type', sa.String(length=10), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='relay'
    )
    op.create_index(op.f('ix_relay_reminder_logs_appointment_id'), 'reminder_logs', ['appointment_id'], unique=False, schema='relay')
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='relay'
    )
    op.create_index(op.f('ix_relay_task_logs_task_id'), 'task_logs', ['task_id'], unique=True, schema='relay')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relay_task_logs_task_id'), table_name='task_logs', schema='relay')
    op.drop_table('task_logs', schema='relay')
    op.drop_index(op.f('ix_relay_reminder_logs_appointment_id'), table_name='reminder_logs', schema='relay')
    op.drop_table('reminder_logs', schema='relay')
    # ### end Alembic commands ###
